[local]
localhost

[mongodb]
mongodb.vnmurthy.online

[redis]
redis.vnmurthy.online

[mysql]
mysql.vnmurthy.online

[rabbitmq]
rabbitmq.vnmurthy.online

[catalogue]
catalogue.vnmurthy.online

[user]
user.vnmurthy.online

[cart]
cart.vnmurthy.online

[shipping]
shipping.vnmurthy.online

[payment]
payment.vnmurthy.online

[frontend]
frontend.vnmurthy.online